GET https://localhost:5236/api/employees
Authorization: Admin
###

GET https://localhost:5236/api/employees?id=b10c13ea-a166-4ab6-a3ea-36efe877da23
Authorization: Admin
random: *
###

###[guid]::NewGuid()
POST  https://localhost:5236/api/employees
Content-Type: application/json
POST_KEY: lol1

{
  "Id":"b10c13ea-a166-4ab6-a3ea-36efe877da23",
  "Name": "test employee"
}
###
DELETE  https://localhost:5236/api/employees?id=b10c13ea-a166-4ab6-a3ea-36efe877da23
###
PUT  https://localhost:5236/api/employees/b10c13ea-a166-4ab6-a3ea-36efe877da23
Content-Type: application/json

{
  "Id":"b10c13ea-a166-4ab6-a3ea-36efe877da23",
  "Name": "test employee 2"
}